# Wrangler configuration for Cloudflare Pages deployment
name = "lauryn-portfolio"
compatibility_date = "2023-06-19"

# This is only used for the Workers configuration which we're not using
# Keep this file for compatibility, actual Pages config is in .cloudflare/pages.toml