# Wrangler configuration for Cloudflare Pages deployment
name = "lauryn-portfolio"
compatibility_date = "2023-06-19"
main = ".vercel/output/static/_worker.js/index.js"

[build]
  command = "npm run build"

[site]
  bucket = ".vercel/output/static"

[env.production]
  NODE_ENV = "production"