# Wrangler configuration for Cloudflare Pages deployment
name = "lauryn-portfolio"
compatibility_date = "2023-06-19"

[build]
  command = "npm run build"
  output_directory = ".next"

[site]
  bucket = ".next"
  entry-point = "./"

[env.production]
  NODE_ENV = "production"